"""
Curated list of top investable trading cards — MLB, NFL, Pokémon.
Prices reflect realistic March 2026 market values (PSA 10 unless noted).
"""

DEFAULT_CARDS = [

    # ══════════════════════════════════════════════════════
    # MLB
    # ══════════════════════════════════════════════════════

    {
        "card": {
            "sport": "MLB",
            "player_name": "Paul Skenes",
            "set_name": "2024 Topps Chrome",
            "card_number": "USC200",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 380,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 185.0,
            "price_7d_avg": 192.0, "price_30d_avg": 210.0, "price_90d_avg": 265.0,
            "price_ath": 420.0, "price_atl": 95.0,
            "sales_volume_7d": 22, "sales_volume_14d": 38, "sales_volume_30d": 95,
            "sell_through_rate": 86.0, "avg_days_to_sell": 1.4, "sales_per_week": 14.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Paul Skenes",
            "set_name": "2024 Topps Series 1",
            "card_number": "330",
            "parallel_type": "Gold Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 18,
            "is_rookie": True, "serial_number": 50, "print_run": 50,
        },
        "market": {
            "current_price": 285.0,
            "price_7d_avg": 310.0, "price_30d_avg": 340.0, "price_90d_avg": 420.0,
            "price_ath": 650.0, "price_atl": 180.0,
            "sales_volume_7d": 8, "sales_volume_14d": 13, "sales_volume_30d": 25,
            "sell_through_rate": 82.0, "avg_days_to_sell": 2.1, "sales_per_week": 7.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Jackson Holliday",
            "set_name": "2024 Topps Chrome",
            "card_number": "USC180",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 290,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 65.0,
            "price_7d_avg": 70.0, "price_30d_avg": 82.0, "price_90d_avg": 110.0,
            "price_ath": 195.0, "price_atl": 32.0,
            "sales_volume_7d": 18, "sales_volume_14d": 30, "sales_volume_30d": 72,
            "sell_through_rate": 72.0, "avg_days_to_sell": 2.2, "sales_per_week": 9.5,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Elly De La Cruz",
            "set_name": "2023 Topps Chrome",
            "card_number": "USC42",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 510,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 92.0,
            "price_7d_avg": 98.0, "price_30d_avg": 115.0, "price_90d_avg": 145.0,
            "price_ath": 280.0, "price_atl": 45.0,
            "sales_volume_7d": 16, "sales_volume_14d": 27, "sales_volume_30d": 68,
            "sell_through_rate": 78.0, "avg_days_to_sell": 2.0, "sales_per_week": 10.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Gunnar Henderson",
            "set_name": "2023 Topps Chrome",
            "card_number": "USC110",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 620,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 110.0,
            "price_7d_avg": 118.0, "price_30d_avg": 135.0, "price_90d_avg": 168.0,
            "price_ath": 310.0, "price_atl": 55.0,
            "sales_volume_7d": 14, "sales_volume_14d": 24, "sales_volume_30d": 60,
            "sell_through_rate": 76.0, "avg_days_to_sell": 2.3, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Bobby Witt Jr.",
            "set_name": "2022 Topps Chrome",
            "card_number": "USC148",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 890,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 78.0,
            "price_7d_avg": 83.0, "price_30d_avg": 95.0, "price_90d_avg": 120.0,
            "price_ath": 220.0, "price_atl": 38.0,
            "sales_volume_7d": 20, "sales_volume_14d": 34, "sales_volume_30d": 85,
            "sell_through_rate": 80.0, "avg_days_to_sell": 1.8, "sales_per_week": 11.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Julio Rodriguez",
            "set_name": "2022 Topps Chrome",
            "card_number": "USC31",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 1100,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 55.0,
            "price_7d_avg": 59.0, "price_30d_avg": 68.0, "price_90d_avg": 88.0,
            "price_ath": 175.0, "price_atl": 28.0,
            "sales_volume_7d": 18, "sales_volume_14d": 30, "sales_volume_30d": 75,
            "sell_through_rate": 74.0, "avg_days_to_sell": 2.2, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Juan Soto",
            "set_name": "2019 Topps Chrome",
            "card_number": "USC25",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 740,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 195.0,
            "price_7d_avg": 205.0, "price_30d_avg": 230.0, "price_90d_avg": 270.0,
            "price_ath": 480.0, "price_atl": 85.0,
            "sales_volume_7d": 12, "sales_volume_14d": 20, "sales_volume_30d": 52,
            "sell_through_rate": 82.0, "avg_days_to_sell": 1.9, "sales_per_week": 8.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Shohei Ohtani",
            "set_name": "2024 Topps Series 1",
            "card_number": "700",
            "parallel_type": "Base",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 3200,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 42.0,
            "price_7d_avg": 45.0, "price_30d_avg": 52.0, "price_90d_avg": 68.0,
            "price_ath": 120.0, "price_atl": 18.0,
            "sales_volume_7d": 35, "sales_volume_14d": 58, "sales_volume_30d": 145,
            "sell_through_rate": 88.0, "avg_days_to_sell": 1.2, "sales_per_week": 18.0,
        },
    },
    {
        "card": {
            "sport": "MLB",
            "player_name": "Corbin Carroll",
            "set_name": "2023 Topps Chrome",
            "card_number": "USC88",
            "parallel_type": "Refractor",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 680,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 48.0,
            "price_7d_avg": 52.0, "price_30d_avg": 62.0, "price_90d_avg": 82.0,
            "price_ath": 160.0, "price_atl": 22.0,
            "sales_volume_7d": 14, "sales_volume_14d": 23, "sales_volume_30d": 58,
            "sell_through_rate": 70.0, "avg_days_to_sell": 2.5, "sales_per_week": 8.0,
        },
    },

    # ══════════════════════════════════════════════════════
    # NFL
    # ══════════════════════════════════════════════════════

    {
        "card": {
            "sport": "NFL",
            "player_name": "Jayden Daniels",
            "set_name": "2024 Panini Prizm",
            "card_number": "331",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 920,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 165.0,
            "price_7d_avg": 175.0, "price_30d_avg": 198.0, "price_90d_avg": 245.0,
            "price_ath": 420.0, "price_atl": 75.0,
            "sales_volume_7d": 18, "sales_volume_14d": 30, "sales_volume_30d": 78,
            "sell_through_rate": 82.0, "avg_days_to_sell": 1.8, "sales_per_week": 11.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Caleb Williams",
            "set_name": "2024 Panini Prizm",
            "card_number": "301",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 1450,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 120.0,
            "price_7d_avg": 128.0, "price_30d_avg": 145.0, "price_90d_avg": 185.0,
            "price_ath": 340.0, "price_atl": 58.0,
            "sales_volume_7d": 22, "sales_volume_14d": 38, "sales_volume_30d": 95,
            "sell_through_rate": 78.0, "avg_days_to_sell": 1.9, "sales_per_week": 12.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Marvin Harrison Jr.",
            "set_name": "2024 Panini Prizm",
            "card_number": "321",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 880,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 145.0,
            "price_7d_avg": 155.0, "price_30d_avg": 175.0, "price_90d_avg": 220.0,
            "price_ath": 390.0, "price_atl": 68.0,
            "sales_volume_7d": 16, "sales_volume_14d": 27, "sales_volume_30d": 68,
            "sell_through_rate": 80.0, "avg_days_to_sell": 2.0, "sales_per_week": 10.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Drake Maye",
            "set_name": "2024 Panini Prizm",
            "card_number": "341",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 760,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 135.0,
            "price_7d_avg": 142.0, "price_30d_avg": 160.0, "price_90d_avg": 200.0,
            "price_ath": 360.0, "price_atl": 62.0,
            "sales_volume_7d": 14, "sales_volume_14d": 24, "sales_volume_30d": 60,
            "sell_through_rate": 76.0, "avg_days_to_sell": 2.2, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Malik Nabers",
            "set_name": "2024 Panini Prizm",
            "card_number": "351",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 640,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 88.0,
            "price_7d_avg": 94.0, "price_30d_avg": 108.0, "price_90d_avg": 138.0,
            "price_ath": 240.0, "price_atl": 40.0,
            "sales_volume_7d": 12, "sales_volume_14d": 20, "sales_volume_30d": 50,
            "sell_through_rate": 72.0, "avg_days_to_sell": 2.4, "sales_per_week": 8.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Brian Thomas Jr.",
            "set_name": "2024 Panini Prizm",
            "card_number": "361",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 520,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 72.0,
            "price_7d_avg": 77.0, "price_30d_avg": 90.0, "price_90d_avg": 118.0,
            "price_ath": 200.0, "price_atl": 32.0,
            "sales_volume_7d": 10, "sales_volume_14d": 17, "sales_volume_30d": 42,
            "sell_through_rate": 68.0, "avg_days_to_sell": 2.8, "sales_per_week": 7.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Patrick Mahomes",
            "set_name": "2017 Panini Prizm",
            "card_number": "269",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 420,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 1850.0,
            "price_7d_avg": 1920.0, "price_30d_avg": 2100.0, "price_90d_avg": 2400.0,
            "price_ath": 4200.0, "price_atl": 680.0,
            "sales_volume_7d": 4, "sales_volume_14d": 7, "sales_volume_30d": 18,
            "sell_through_rate": 88.0, "avg_days_to_sell": 3.5, "sales_per_week": 3.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Josh Allen",
            "set_name": "2018 Panini Prizm",
            "card_number": "212",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 380,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 520.0,
            "price_7d_avg": 545.0, "price_30d_avg": 590.0, "price_90d_avg": 680.0,
            "price_ath": 1200.0, "price_atl": 180.0,
            "sales_volume_7d": 6, "sales_volume_14d": 10, "sales_volume_30d": 26,
            "sell_through_rate": 85.0, "avg_days_to_sell": 2.8, "sales_per_week": 4.5,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "CJ Stroud",
            "set_name": "2023 Panini Prizm",
            "card_number": "301",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 1200,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 95.0,
            "price_7d_avg": 100.0, "price_30d_avg": 115.0, "price_90d_avg": 148.0,
            "price_ath": 280.0, "price_atl": 42.0,
            "sales_volume_7d": 14, "sales_volume_14d": 24, "sales_volume_30d": 60,
            "sell_through_rate": 74.0, "avg_days_to_sell": 2.3, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "NFL",
            "player_name": "Bo Nix",
            "set_name": "2024 Panini Prizm",
            "card_number": "371",
            "parallel_type": "Silver",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 580,
            "is_rookie": True, "serial_number": None,
        },
        "market": {
            "current_price": 58.0,
            "price_7d_avg": 62.0, "price_30d_avg": 72.0, "price_90d_avg": 95.0,
            "price_ath": 175.0, "price_atl": 25.0,
            "sales_volume_7d": 10, "sales_volume_14d": 17, "sales_volume_30d": 42,
            "sell_through_rate": 66.0, "avg_days_to_sell": 3.0, "sales_per_week": 7.0,
        },
    },

    # ══════════════════════════════════════════════════════
    # Pokémon
    # ══════════════════════════════════════════════════════

    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Umbreon VMAX",
            "set_name": "2021 Evolving Skies",
            "card_number": "215",
            "parallel_type": "Alternate Art",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 3800,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 385.0,
            "price_7d_avg": 400.0, "price_30d_avg": 430.0, "price_90d_avg": 510.0,
            "price_ath": 780.0, "price_atl": 165.0,
            "sales_volume_7d": 12, "sales_volume_14d": 20, "sales_volume_30d": 52,
            "sell_through_rate": 82.0, "avg_days_to_sell": 2.2, "sales_per_week": 7.5,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Rayquaza VMAX",
            "set_name": "2021 Evolving Skies",
            "card_number": "217",
            "parallel_type": "Alternate Art",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 4200,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 265.0,
            "price_7d_avg": 278.0, "price_30d_avg": 305.0, "price_90d_avg": 370.0,
            "price_ath": 560.0, "price_atl": 110.0,
            "sales_volume_7d": 14, "sales_volume_14d": 24, "sales_volume_30d": 60,
            "sell_through_rate": 79.0, "avg_days_to_sell": 2.0, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Charizard ex",
            "set_name": "2023 Obsidian Flames",
            "card_number": "228",
            "parallel_type": "Special Illustration Rare",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 6200,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 175.0,
            "price_7d_avg": 183.0, "price_30d_avg": 205.0, "price_90d_avg": 255.0,
            "price_ath": 420.0, "price_atl": 68.0,
            "sales_volume_7d": 28, "sales_volume_14d": 48, "sales_volume_30d": 120,
            "sell_through_rate": 88.0, "avg_days_to_sell": 1.2, "sales_per_week": 18.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Pikachu VMAX",
            "set_name": "2022 Crown Zenith",
            "card_number": "GG47",
            "parallel_type": "Galarian Gallery",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 5800,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 88.0,
            "price_7d_avg": 93.0, "price_30d_avg": 105.0, "price_90d_avg": 132.0,
            "price_ath": 240.0, "price_atl": 35.0,
            "sales_volume_7d": 24, "sales_volume_14d": 40, "sales_volume_30d": 100,
            "sell_through_rate": 84.0, "avg_days_to_sell": 1.5, "sales_per_week": 14.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Mew VMAX",
            "set_name": "2022 Fusion Strike",
            "card_number": "269",
            "parallel_type": "Alternate Art",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 7100,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 125.0,
            "price_7d_avg": 132.0, "price_30d_avg": 148.0, "price_90d_avg": 182.0,
            "price_ath": 320.0, "price_atl": 52.0,
            "sales_volume_7d": 20, "sales_volume_14d": 34, "sales_volume_30d": 85,
            "sell_through_rate": 80.0, "avg_days_to_sell": 1.8, "sales_per_week": 12.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Gardevoir ex",
            "set_name": "2022 Silver Tempest",
            "card_number": "TG29",
            "parallel_type": "Trainer Gallery",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 2900,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 145.0,
            "price_7d_avg": 152.0, "price_30d_avg": 170.0, "price_90d_avg": 210.0,
            "price_ath": 380.0, "price_atl": 58.0,
            "sales_volume_7d": 14, "sales_volume_14d": 24, "sales_volume_30d": 60,
            "sell_through_rate": 78.0, "avg_days_to_sell": 2.0, "sales_per_week": 9.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Miraidon ex",
            "set_name": "2023 Scarlet & Violet",
            "card_number": "253",
            "parallel_type": "Special Illustration Rare",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 8400,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 62.0,
            "price_7d_avg": 66.0, "price_30d_avg": 76.0, "price_90d_avg": 98.0,
            "price_ath": 178.0, "price_atl": 22.0,
            "sales_volume_7d": 30, "sales_volume_14d": 50, "sales_volume_30d": 125,
            "sell_through_rate": 82.0, "avg_days_to_sell": 1.4, "sales_per_week": 18.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Charizard ex",
            "set_name": "2023 Paldea Evolved",
            "card_number": "199",
            "parallel_type": "Special Illustration Rare",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 9800,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 52.0,
            "price_7d_avg": 56.0, "price_30d_avg": 64.0, "price_90d_avg": 82.0,
            "price_ath": 150.0, "price_atl": 18.0,
            "sales_volume_7d": 35, "sales_volume_14d": 58, "sales_volume_30d": 145,
            "sell_through_rate": 85.0, "avg_days_to_sell": 1.3, "sales_per_week": 20.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Lugia V",
            "set_name": "2022 Silver Tempest",
            "card_number": "TG21",
            "parallel_type": "Trainer Gallery",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 3100,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 115.0,
            "price_7d_avg": 122.0, "price_30d_avg": 138.0, "price_90d_avg": 170.0,
            "price_ath": 295.0, "price_atl": 45.0,
            "sales_volume_7d": 12, "sales_volume_14d": 20, "sales_volume_30d": 50,
            "sell_through_rate": 76.0, "avg_days_to_sell": 2.2, "sales_per_week": 8.0,
        },
    },
    {
        "card": {
            "sport": "Pokemon",
            "player_name": "Iono",
            "set_name": "2023 Paldea Evolved",
            "card_number": "185",
            "parallel_type": "Special Illustration Rare",
            "is_graded": True, "grade_company": "PSA", "grade": "10",
            "population": 4500,
            "is_rookie": False, "serial_number": None,
        },
        "market": {
            "current_price": 195.0,
            "price_7d_avg": 205.0, "price_30d_avg": 228.0, "price_90d_avg": 275.0,
            "price_ath": 480.0, "price_atl": 80.0,
            "sales_volume_7d": 10, "sales_volume_14d": 17, "sales_volume_30d": 42,
            "sell_through_rate": 74.0, "avg_days_to_sell": 2.5, "sales_per_week": 7.0,
        },
    },
]
